### ISSUE TITLE
Repeat Weekdays

### ISSUE THREAD

**Issue by mroswell** [doggan/habit-template-gen#1]
I like the concept. When I choose November I get:
- November 31 (Which does not exist)
- Duplicate Tuesdays (Nov 9 and Nov 10)
- Duplicate Thursdays (Dec 9 and Dec 10)

I'll definitely use this if these issues are fixed.

**Comment by doggan** [comment]
These issue should be fixed now :) Thanks for reporting (7da724b65a238a9d8e2407dc4737df95f54a9360, 1414d17aec400a97602804b736601a64397678ec).
