### ISSUE TITLE
Better UX : form validation instead of generating empty pdf on no habit added

### ISSUE THREAD

**Issue by battinleo** [doggan/habit-template-gen#6]
Hey, it would be a bit better if some sort of validation would prompt the user on the page to add at least one habit if none was added, and prevent the doc from being generated in such case.

I'd be glad to do it as a JS exercise for myself !

**Comment by doggan** [comment]
Hello! It looks like I'm currently showing an error message but the download button is still active:

<img width="727" alt="image" src="https://github.com/doggan/habit-template-gen/assets/517857/7babf88e-806e-429b-81d8-9184f7c67257">

I'm open to a PR if you want to improve this. At the very least the button should be disabled when there are no habits to prevent downloading an empty pdf.

Thanks for bringing this up.
